class Autogenerated {
  Content content;

  Autogenerated({this.content});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    content =
        json['content'] != null ? new Content.fromJson(json['content']) : null;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    if (this.content != null) {
      data['content'] = this.content.toJson();
    }
    return data;
  }
}

class Content {
  List<Stories> stories;
  List<Posts> posts;

  Content({this.stories, this.posts});

  Content.fromJson(Map<String, dynamic> json) {
    if (json['stories'] != null) {
      stories = new List<Stories>();
      json['stories'].forEach((v) {
        stories.add(new Stories.fromJson(v));
      });
    }
    if (json['posts'] != null) {
      posts = new List<Posts>();
      json['posts'].forEach((v) {
        posts.add(new Posts.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    if (this.stories != null) {
      data['stories'] = this.stories.map((v) => v.toJson()).toList();
    }
    if (this.posts != null) {
      data['posts'] = this.posts.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class Stories {
  String media;
  String type;
  String title;
  String user;
  int views;
  String createdAt;

  Stories(
      {this.media,
      this.type,
      this.title,
      this.user,
      this.views,
      this.createdAt});

  Stories.fromJson(Map<String, dynamic> json) {
    media = json['media'];
    type = json['type'];
    title = json['title'];
    user = json['user'];
    views = json['views'];
    createdAt = json['created_at'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['media'] = this.media;
    data['type'] = this.type;
    data['title'] = this.title;
    data['user'] = this.user;
    data['views'] = this.views;
    data['created_at'] = this.createdAt;
    return data;
  }
}

class Posts {
  String media;
  String type;
  String title;
  String user;
  int likes;
  String createdAt;
  List<Comments> comments;

  Posts(
      {this.media,
      this.type,
      this.title,
      this.user,
      this.likes,
      this.createdAt,
      this.comments});

  Posts.fromJson(Map<String, dynamic> json) {
    media = json['media'];
    type = json['type'];
    title = json['title'];
    user = json['user'];
    likes = json['likes'];
    createdAt = json['created_at'];
    if (json['comments'] != null) {
      comments = new List<Comments>();
      json['comments'].forEach((v) {
        comments.add(new Comments.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['media'] = this.media;
    data['type'] = this.type;
    data['title'] = this.title;
    data['user'] = this.user;
    data['likes'] = this.likes;
    data['created_at'] = this.createdAt;
    if (this.comments != null) {
      data['comments'] = this.comments.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class Comments {
  String user;
  String comment;
  String createdAt;

  Comments({this.user, this.comment, this.createdAt});

  Comments.fromJson(Map<String, dynamic> json) {
    user = json['user'];
    comment = json['comment'];
    createdAt = json['created_at'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['user'] = this.user;
    data['comment'] = this.comment;
    data['created_at'] = this.createdAt;
    return data;
  }
}
